FROM docker:18.06.1-ce-git
RUN apk add -U curl
RUN cd ~ && curl -sL https://github.com/digitalocean/doctl/releases/download/v1.11.0/doctl-1.11.0-linux-amd64.tar.gz | tar -xzv && mv ~/doctl /usr/local/bin
