FROM circleci/openjdk:8-jdk-node-browsers
RUN sudo apt-get update
RUN sudo apt-get install lftp
RUN sudo npm install -g selenium-side-runner webdriver-manager
RUN sudo webdriver-manager update --versions.chrome=`google-chrome --product-version`
